//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JS.Suite.BusinessLogic.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JS.Suite.BusinessLogic.Resource.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Label.
        /// </summary>
        public static string _Label {
            get {
                return ResourceManager.GetString("_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Local Password.
        /// </summary>
        public static string AddALocalPassword {
            get {
                return ResourceManager.GetString("AddALocalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Login.
        /// </summary>
        public static string AddALogin {
            get {
                return ResourceManager.GetString("AddALogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured..
        /// </summary>
        public static string AnErrorHasOccured {
            get {
                return ResourceManager.GetString("AnErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string AnErrorOccurredWhileProcessingYourRequest {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileProcessingYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user has already confirmed this email address..
        /// </summary>
        public static string AnotherUserHasAlreadyConfirmedThisEmailAddress {
            get {
                return ResourceManager.GetString("AnotherUserHasAlreadyConfirmedThisEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log.
        /// </summary>
        public static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log Summary.
        /// </summary>
        public static string ApplicationLogSummary {
            get {
                return ResourceManager.GetString("ApplicationLogSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumping Salamander.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account..
        /// </summary>
        public static string AssociateYour_Account {
            get {
                return ResourceManager.GetString("AssociateYour_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To My Collections.
        /// </summary>
        public static string BackToMyCollections {
            get {
                return ResourceManager.GetString("BackToMyCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the Home Screen.
        /// </summary>
        public static string BackToTheHomeScreen {
            get {
                return ResourceManager.GetString("BackToTheHomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the Login Screen.
        /// </summary>
        public static string BackToTheLoginScreen {
            get {
                return ResourceManager.GetString("BackToTheLoginScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Confirm Email.
        /// </summary>
        public static string CantConfirmEmail {
            get {
                return ResourceManager.GetString("CantConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Local Password.
        /// </summary>
        public static string ChangeYourLocalPassword {
            get {
                return ResourceManager.GetString("ChangeYourLocalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to confirm your email address!.
        /// </summary>
        public static string ClickHereToConfirmYourEmailAddress {
            get {
                return ResourceManager.GetString("ClickHereToConfirmYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to reset your password..
        /// </summary>
        public static string ClickHereToResetYourPassword {
            get {
                return ResourceManager.GetString("ClickHereToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Email Sent.
        /// </summary>
        public static string ConfirmationEmailSent {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Collection.
        /// </summary>
        public static string CreateNewCollection {
            get {
                return ResourceManager.GetString("CreateNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Item.
        /// </summary>
        public static string CreateNewItem {
            get {
                return ResourceManager.GetString("CreateNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your Password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception.
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Inner Exception.
        /// </summary>
        public static string InnerInnerException {
            get {
                return ResourceManager.GetString("InnerInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Inner Inner Exception.
        /// </summary>
        public static string InnerInnerInnerException {
            get {
                return ResourceManager.GetString("InnerInnerInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to receive email notifications from us we need to confirm this email address.  Please click the link below to complete the confirmation process..
        /// </summary>
        public static string InOrderToReceiveEmailNotifications {
            get {
                return ResourceManager.GetString("InOrderToReceiveEmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link your {0} Account.
        /// </summary>
        public static string LinkYour_Account {
            get {
                return ResourceManager.GetString("LinkYour_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in failed with external provider..
        /// </summary>
        public static string LogInFailedWithExternalProvider {
            get {
                return ResourceManager.GetString("LogInFailedWithExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string LogInUsingYour_Account {
            get {
                return ResourceManager.GetString("LogInUsingYour_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with {0}.
        /// </summary>
        public static string LogInWith_ {
            get {
                return ResourceManager.GetString("LogInWith_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your User Account.
        /// </summary>
        public static string ManageYourUserAccount {
            get {
                return ResourceManager.GetString("ManageYourUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Collections.
        /// </summary>
        public static string MyCollections {
            get {
                return ResourceManager.GetString("MyCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Games.
        /// </summary>
        public static string MyGames {
            get {
                return ResourceManager.GetString("MyGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection.
        /// </summary>
        public static string NewCollection {
            get {
                return ResourceManager.GetString("NewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to Jumping Salamander?.
        /// </summary>
        public static string NewtoJumpingSalamander {
            get {
                return ResourceManager.GetString("NewtoJumpingSalamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string PleaseCheckYourEmailToResetYourPassword {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmailToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking the link below..
        /// </summary>
        public static string PleaseResetYourPasswordByClickingTheLinkBelow {
            get {
                return ResourceManager.GetString("PleaseResetYourPasswordByClickingTheLinkBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} Account.
        /// </summary>
        public static string Remove_Account {
            get {
                return ResourceManager.GetString("Remove_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a Login.
        /// </summary>
        public static string RemoveALogin {
            get {
                return ResourceManager.GetString("RemoveALogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Jumping Salamander Password.
        /// </summary>
        public static string ResetYourJumpingSalamanderPassword {
            get {
                return ResourceManager.GetString("ResetYourJumpingSalamanderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a Password Reset Email.
        /// </summary>
        public static string SendAPasswordResetEmail {
            get {
                return ResourceManager.GetString("SendAPasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the Password Reset Email.
        /// </summary>
        public static string SendThePasswordResetEmail {
            get {
                return ResourceManager.GetString("SendThePasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks,.
        /// </summary>
        public static string ThanksComma {
            get {
                return ResourceManager.GetString("ThanksComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for joining Jumping Salamander!.
        /// </summary>
        public static string ThankYouForJoiningJumpingSalamander {
            get {
                return ResourceManager.GetString("ThankYouForJoiningJumpingSalamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {1} and {0} do not match..
        /// </summary>
        public static string The_And_DoNotMatch {
            get {
                return ResourceManager.GetString("The_And_DoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string The_FieldIsNotAValidEmailAddress {
            get {
                return ResourceManager.GetString("The_FieldIsNotAValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string The_MustBeAtLeast_CharactersLong {
            get {
                return ResourceManager.GetString("The_MustBeAtLeast_CharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external log in was added..
        /// </summary>
        public static string TheExternalLogInWasAdded {
            get {
                return ResourceManager.GetString("TheExternalLogInWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external log in was removed..
        /// </summary>
        public static string TheExternalLogInWasRemoved {
            get {
                return ResourceManager.GetString("TheExternalLogInWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user either does not exist or is not confirmed..
        /// </summary>
        public static string TheUserEitherDoesNotExistOrIsNotConfirmed {
            get {
                return ResourceManager.GetString("TheUserEitherDoesNotExistOrIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is unavailable..
        /// </summary>
        public static string This_IsUnavailable {
            get {
                return ResourceManager.GetString("This_IsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out for too many failed log in attempts.  Please try again in 2 hours..
        /// </summary>
        public static string ThisAccountHasBeenLockedOut {
            get {
                return ResourceManager.GetString("ThisAccountHasBeenLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Collection Items.
        /// </summary>
        public static string TotalCollectionItems {
            get {
                return ResourceManager.GetString("TotalCollectionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Log.
        /// </summary>
        public static string TrafficLog {
            get {
                return ResourceManager.GetString("TrafficLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Log Location Summary.
        /// </summary>
        public static string TrafficLogLocationSummary {
            get {
                return ResourceManager.GetString("TrafficLogLocationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Email Address with Jumping Salamander.
        /// </summary>
        public static string VerifyYourEmailAddressWithJumpingSalamander {
            get {
                return ResourceManager.GetString("VerifyYourEmailAddressWithJumpingSalamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry.  This issue has been logged and will be looked into shortly..
        /// </summary>
        public static string WeReSorryThisIssueHasBeenLoggedAndWillBeLookedIntoShortly {
            get {
                return ResourceManager.GetString("WeReSorryThisIssueHasBeenLoggedAndWillBeLookedIntoShortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
    }
}
